export const diagnosisBase = "/api/diagnoses";

export const diagnosisAgents = ["seo_audit", "ai_visibility", "internal_linking", "serp_competitor", "keyword_cluster", "metadata", "schema_markup", "content_brief", "local_seo", "content_optimizer", "question_discovery", "answer_gap", "answer_optimization", "faq_intelligence", "question_intent", "answer_structure", "aeo_opportunity"];
export const diagnosisLabels: Record<string, string> = {
  capture: "Capture shared page evidence", seo_audit: "SEO/AEO Audit", ai_visibility: "AI Visibility", internal_linking: "Internal Linking", serp_competitor: "SERP & Competitor", keyword_cluster: "Keyword Clustering", metadata: "Metadata", schema_markup: "Schema Markup", content_brief: "Content Brief", local_seo: "Local SEO", content_optimizer: "Content Optimizer", question_discovery: "Question Discovery", answer_gap: "Answer Gap", answer_optimization: "Answer Optimization", faq_intelligence: "FAQ Intelligence", question_intent: "Question Intent", answer_structure: "Answer Structure", aeo_opportunity: "AEO Opportunity", report: "Assemble management report",
};
const AGENT_ROUTE_SLUG: Record<string, string> = {
  seo_audit: "seo-audit", ai_visibility: "ai-visibility", internal_linking: "internal-linking",
  serp_competitor: "serp-competitor", keyword_cluster: "keyword-cluster",
  metadata: "meta-title-description", schema_markup: "schema-markup",
  content_brief: "content-brief", local_seo: "local-seo", content_optimizer: "content-optimizer",
  question_discovery: "question-discovery",
  answer_gap: "answer-gap",
  answer_optimization: "answer-optimization",
  faq_intelligence: "faq-intelligence",
  question_intent: "question-intent",
  answer_structure: "answer-structure",
  aeo_opportunity: "aeo-opportunity",
};
export function diagnosisAgentRunHref(agent: string, runId: string): string {
  return `/agents/${AGENT_ROUTE_SLUG[agent]}/runs/${runId}`;
}
export type Evidence = { id: string; title?: string; source_label?: string; source_kind?: string; source_url: string; observed: string; observed_value?: string; expected_value?: string | null; location?: string; excerpt?: string | null; fix_example?: string | null; fix_label?: string | null; presentation_kind?: "standard"|"json_parse_error"|"schema_identity_mismatch"|"metadata_length"|"image_alt"|"serp_sample"; captured_at: string; method: string; confidence?: string; support_type?: string; verification?: string; visual_url?: string | null; agent: string };
export type Finding = { id: string; lineage_id?: string; title: string; observation: string; business_relevance: string; action: string; classification: string; classification_label?: string; priority: string; primary_agent: string; supporting_agents: string[]; evidence_ids: string[]; owner: string; completion_criteria: string };
export type EvidenceExplanation = { evidence_id: string; plain_language: string; example: string };
export type CaseManagement = { section_kind?: "finding" | "assessment"; source: string; issue_identified: string; finding_ids: string[]; evidence_ids: string[]; evidence_explanations: EvidenceExplanation[]; why_management_should_care: string; other_findings: string[]; recommended_actions: string[]; limitation: string };
export type Case = { agent: string; agent_label: string; heading: string; status: string; output_quality?: string; contribution_role?: "primary"|"supporting"|"assessment"; contribution_label?: string; run_id: string | null; finding_ids: string[]; observations: string[]; proposed_outputs: string[]; limitations: string[]; owner: string; urgency?: {label:string; timeframe:string}; management?: CaseManagement };
export type AgentScoreArea = { label: string; score: number; basis: string };
export type AgentMeasurement = { label: string; value: string; note: string };
export type AgentBenchmark = { label: string; observed: string; target: string; basis: string; evidence_id: string };
export type AgentAction = { finding_id: string | null; title: string; action: string; rationale: string; owner: string; priority: string; impact: string; effort: string; timeframe: string; steps: string[]; done_when: string };
export type AgentFix = { evidence_id: string; title: string; context: string; current: string; replacement: string; language: string };
export type AgentSuccessMetric = { metric: string; current: string; target: string; window: string; basis: string };
export type AgentTrace = { step: string; status: string; reference: string; detail: string; at: string };
export type AgentMethod = { title: string; description: string };
export type DiscoveredQuestion = { id:string; lineage_id:string; question:string; topic:string; intent:string; journey_stage:string; page_coverage:"explicit"|"implicit"|"absent"|"unknown"; coverage_basis:string; coverage_role?:"triage_hint"|"hypothesis_preview"; evidence_status:"observed"|"inferred"; confidence:string; source_types:string[]; source_urls:string[]; variants?:string[]; priority_score:number; handoffs:{seo:string;aeo:string;geo:string} };
export type SourceLedgerItem = {source_type:string;status:"captured"|"unavailable"|"planning_only";query:string|null;observed_count:number;observed_at:string|null};
export type AgentHandoff = {target_agent:string;target_label:string;question_ids:string[];title:string;reason:string;source_agent?:string;source_agent_label?:string;engine?:"SEO"|"AEO"|"GEO"};
export type AnswerAssessment = {question_id:string;lineage_id:string;question:string;topic?:string;intent?:string;question_source_types:string[];evidence_status:string;status:"answered"|"partial"|"missing"|"unable_to_verify";reason:string;answer_quality_score:number;dimensions:{directness:number;completeness:number;extractability:number;factual_support:number};passage:{excerpt:string;source_url?:string;location?:string}|null};
export type OptimizedAnswer = {question_id:string;lineage_id:string;question:string;topic?:string;intent?:string;priority:string;priority_score:number;status:"drafted"|"fallback_extractive"|"needs_facts";fallback_reason:"provider_unavailable"|"no_draft_returned"|"validation_failed"|null;draft_answer:string|null;word_count:number|null;within_target_length:boolean|null;grounding_verified:boolean|null;checklist_action:string|null;source_excerpt:string|null;source_url?:string|null;reason:string};
export type FaqEntry = {category:string;lineage_id:string|null;observed_question_count:number;unresolved_questions:string[];status:"covered"|"needs_editorial_review"|"not_covered"|"not_assessed";answer:string|null;source_url?:string|null;evidence_source:"answer_optimization"|"answer_gap"|null;question:string;question_id:string|null;reason:string;content_gap_action:string|null};
export type IntentDistributionRow = {intent:"Discover"|"Evaluate"|"Plan"|"Book"|"Manage";count:number;observed_count:number;hypothesis_count:number;share:number};
export type ReprioritizedGap = {question_id:string;question:string;evidence_status:string;journey_stage:"Discover"|"Evaluate"|"Plan"|"Book"|"Manage";intent:string;topic:string;priority_score:number;gap_status:"answered"|"partial"|"missing"|null;weighted_priority_score:number;priority:"high"|"medium"|"low";reason:string};
export type ContentStrategyRow = {intent:"Discover"|"Evaluate"|"Plan"|"Book"|"Manage";recommended_agent:string;recommended_agent_label:string;reason:string;question_count:number};
export type StructureEntry = {question_id:string;lineage_id:string;question:string;question_type:string;answer_status:string;structure_status:"strong"|"needs_review"|"weak"|"unable_to_locate";structure_score:number|null;assessment_confidence:number;locator_method:string;heading:string|null;heading_level:string|null;element_type:string|null;position:number|null;interactive:boolean|null;hidden:boolean|null;word_count:number;source_url:string;source_excerpt:string;issues:string[];recommended_action:string|null;dimensions:Record<string,number>};
export type AeoOpportunity = {question_id:string;question_ids:string[];lineage_id:string;question:string;evidence_status:string;assessment_confidence:number;issue:string;issue_facets:string[];recommended_action:string;primary_action:string;supporting_actions:string[];completion_check:string;journey_stage:string;priority_score:number;priority:"high"|"medium"|"low";priority_factors:Record<string,number>;queue:"now"|"next"|"later"|"blocked";effort:"low"|"medium"|"high";owner:string;blockers:string[];dependencies:string[];source_agents:string[];reason:string;source_url:string;source_excerpt:string|null};
export type AeoResearchOpportunity = {lineage_id:string;question:string;queue:"research";reason:string;source_types:string[];priority_score:number};
export type AgentReport = { agent: string; agent_label: string; heading: string; score: number; score_status: {label:string;tone:string}; score_basis: string; score_kind?:"readiness"|"evidence_confidence"|"unscored"; score_breakdown: AgentScoreArea[]; assessed_area_count: number; critical_count: number; warning_count: number; finding_count: number; executive_summary: string; management_relevance: string; measurements: AgentMeasurement[]; finding_ids: string[]; evidence_ids: string[]; benchmarks: AgentBenchmark[]; action_plan: AgentAction[]; fixes: AgentFix[]; success_metrics: AgentSuccessMetric[]; trace: AgentTrace[]; method: AgentMethod[]; limitations: string[]; output_quality: string; question_landscape?:DiscoveredQuestion[]; question_clusters?:{label:string;question_count:number}[]; discovery_confidence_score?:number|null; evidence_quality?:{status:"verified"|"partial"|"insufficient";score:number;observed_source_types:string[];observed_question_count:number}|null; source_ledger?:SourceLedgerItem[]; answer_gap_candidate_ids?:string[]; recommended_agent_handoffs?:AgentHandoff[]; answer_coverage?:AnswerAssessment[]; assessment_confidence_score?:number|null; optimized_answers?:OptimizedAnswer[]; optimization_coverage_score?:number|null; faq_entries?:FaqEntry[]; faq_coverage_score?:number|null; intent_distribution?:IntentDistributionRow[]; reprioritized_gaps?:ReprioritizedGap[]; content_strategy?:ContentStrategyRow[]; high_value_readiness_score?:number|null; structure_entries?:StructureEntry[]; answer_structure_score?:number|null; aeo_opportunities?:AeoOpportunity[]; aeo_research_opportunities?:AeoResearchOpportunity[]; aeo_roadmap?:Record<"now"|"next"|"later"|"blocked"|"research",string[]>; aeo_opportunity_score?:number|null };
export type SessionScore = { score: number; score_status: {label:string;tone:string}; agent_count: number; finding_count: number; critical_count: number; score_basis: string };
export type EngineScore = { engine:"SEO"|"AEO"|"GEO"; score:number; score_kind?:"readiness"|"evidence_confidence"|"unscored"; score_status:{label:string;tone:string}; agent_count:number; finding_count:number; critical_count:number; warning_count:number; weakest_agent:string; weakest_agent_label:string; strongest_agent:string; strongest_agent_label:string };
export type IntelligencePriority = { id:string; rank:number; finding_id:string|null; title:string; action:string; rationale:string; risk_if_delayed:string; agent:string; agent_label:string; engine:"SEO"|"AEO"|"GEO"; priority:string; impact:string; effort:string; timeframe:string; owner:string; done_when:string; priority_score:number; score_factors:{severity:number;impact:number;effort:number;engine_weakness:number} };
export type SessionIntelligence = { engine_scores:EngineScore[]; missing_engines:("SEO"|"AEO"|"GEO")[]; decision_summary:string; constraint:{engine:"SEO"|"AEO"|"GEO";score:number}|null; priorities:IntelligencePriority[]; quick_win_ids:string[]; risk_ids:string[]; delivery:{now:string[];next:string[];later:string[]}; recommended_agent_handoffs:AgentHandoff[]; method:string };
export type ManagementReport = { title: string; overview: string; page_url: string; research_query: string; identity?: {property_name:string; brand?:string|null; destination?:string|null; confidence:string; supporting_sources:string[]; rejected_candidates:{value:string;reason:string}[]; branded_query:string; generic_query?:string|null}; captured_at: string | null; generated_at: string; version: number; scope: string[]; findings: Finding[]; cases: Case[]; evidence: Record<string, Evidence>; agent_reports?: Record<string, AgentReport>; session_score?: SessionScore; session_intelligence?: SessionIntelligence; limitations: string[]; management_editor?: {status:string; source:string; model?:string; note?:string; edited_cases?:number; deterministic_cases?:number}; narrative: { source: string; text?: string; status?: string; note?: string } };
export type Diagnosis = { id: string; status: string; request: { page_url: string; audience: string; business_goal: string; page_limit: number; country: string; language: string; model_provider: string; run_mode: "diagnosis" | "individual"; selected_agents: string[] }; created_at: string; tasks: Record<string, { status: string; attempts: number; error: string | null; run_id: string | null; result: { reason?: string } }>; report: ManagementReport | null };
export type HistoryItem = { id: string; url: string; status: string; created_at: string; run_mode: "diagnosis" | "individual"; selected_agents: string[]; finding_count: number };
export type HistoryPage = { items: HistoryItem[]; page: number; page_size: number; total: number; total_pages: number };

export async function diagnosisRequest<T>(path: string, body?: unknown, method?: string): Promise<T> {
  const response = await fetch(`${diagnosisBase}${path}`, { method: method || (body ? "POST" : "GET"), credentials: "include", cache: "no-store", headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  if (!response.ok) {
    const error = await response.json().catch(() => null);
    const detail = error?.detail;
    throw new Error(typeof detail === "string" ? detail : Array.isArray(detail) ? detail.map((e: {msg: string}) => e.msg).join("; ") : `Request failed (${response.status}). Please retry.`);
  }
  if (response.status === 204) return undefined as T;
  return response.json();
}
