import { CheckIcon, SearchIcon, SparkIcon } from "@/components/icons";
import { LoginForm } from "@/components/login-form";

export default function LoginPage() {
  return <main className="grid min-h-screen bg-[#f7f9fa] lg:grid-cols-[1.05fr_.95fr]">
    <section className="login-grid relative hidden min-h-screen overflow-hidden bg-[#09110b] px-10 py-10 text-[#f2f5f1] lg:flex lg:flex-col lg:justify-between xl:px-16 xl:py-12">
      <header className="relative flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef5ef] text-[#0b5b37]"><SparkIcon className="h-5 w-5"/></span><span className="text-base font-semibold uppercase tracking-[.08em]">Stellar Agents</span></div><span className="flex items-center gap-2 text-xs text-[#9aae9e]"><i className="h-2 w-2 rounded-full bg-[#40bd73]"/>Live intelligence</span></header>
      <div className="relative max-w-[700px] py-10"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-[#32a968]">Search intelligence workspace</p><h1 className="mt-6 text-4xl font-semibold leading-[1.08] tracking-[-.035em] xl:text-[60px]">Make every page<br/>easier to find,<br/>understand, and cite.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#93a297]">Coordinate specialist SEO, AEO, content and website agents from one precise workspace. Turn audits into clear, prioritized action.</p>
        <div className="mt-10 max-w-[820px] border border-[#233027] bg-[#0e1711]/90"><div className="flex items-center justify-between border-b border-[#233027] px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#27a55d] text-[#06110a]"><SearchIcon className="h-4 w-4"/></span><div><p className="text-sm font-semibold">Website diagnosis</p><p className="text-[11px] text-[#829187]">One URL · selected specialists</p></div></div><span className="text-[11px] font-semibold uppercase tracking-[.15em] text-[#37ba70]">Ready</span></div><div className="grid sm:grid-cols-3"><div className="border-b border-[#233027] p-5 sm:border-b-0 sm:border-r"><p className="text-[11px] uppercase tracking-[.12em] text-[#829187]">Active agents</p><p className="mt-4 text-3xl font-semibold">10</p><p className="mt-3 text-xs text-[#36b86d]">Evidence-backed checks</p></div><div className="border-b border-[#233027] p-5 sm:border-b-0 sm:border-r"><p className="text-[11px] uppercase tracking-[.12em] text-[#829187]">Output</p><p className="mt-4 text-3xl font-semibold">1</p><p className="mt-3 text-xs text-[#829187]">Management report</p></div><div className="p-5"><p className="text-[11px] uppercase tracking-[.12em] text-[#829187]">Coverage</p><div className="mt-6 flex h-12 items-end gap-2">{[42,60,50,76,66,83,74,94,84,100].map((height,index)=><i key={index} className="w-full bg-[#378c57]" style={{height:`${height}%`}}/>)}</div><p className="mt-3 text-[11px] text-[#829187]">SEO · AEO · Content</p></div></div></div>
      </div>
      <footer className="relative text-xs text-[#607065]">Stellar Agents · Evidence before recommendations</footer>
    </section>
    <section className="flex min-h-screen items-center justify-center px-6 py-10 sm:px-10"><div className="w-full max-w-[440px]"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-[#007846]">Agent command center</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] text-[#171b1d]">Sign in</h2><p className="mt-3 max-w-md text-base leading-7 text-[#6d7579]">Enter the demo workspace to run all specialist agents and review complete reports.</p><div className="my-7 flex items-center gap-3 border-y border-[#dfe3e2] py-4 text-[13px] leading-5 text-[#6d7579]"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#f0f3f2] text-[#1a2220]"><CheckIcon className="h-4 w-4"/></span>No setup required. Your saved sessions remain available in the workspace.</div><LoginForm/><div className="mt-6 border-l-2 border-[#07814d] bg-[#f2f4f3] px-4 py-3 text-[13px]"><div className="flex justify-between gap-5"><span className="text-[#737b7f]">Demo email</span><code>demo@stellar.ai</code></div><div className="mt-2 flex justify-between gap-5"><span className="text-[#737b7f]">Password</span><code>stellar123</code></div></div><p className="mt-8 text-center text-xs text-[#8b9295]">A guided product demonstration · No account creation required</p></div></section>
  </main>;
}
