"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { CheckIcon } from "@/components/icons";
import { getVisibilityAudit, processVisibilityAudit, retryVisibilityAudit, type VisibilityFinding, type VisibilityResponse, type VisibilityResult } from "@/lib/ai-visibility-api";

const stages = ["queued","validating","crawling","analyzing","scoring","complete"];
const labels: Record<string,string> = {queued:"Queued",validating:"Checking URL and scope",crawling:"Reading public pages",analyzing:"Evaluating observed signals",scoring:"Building the transparent scorecard",complete:"AI visibility audit complete",failed:"Audit failed"};
function severityStyle(value:string) { return value === "critical" ? "bg-red-50 text-red-700" : value === "important" ? "bg-amber-50 text-amber-800" : "bg-blue-50 text-blue-700" }
function Progress({run}:{run:VisibilityResponse|null}) { const stage=run?.audit.stage || "queued", progress=run?.audit.progress || 0, current=stages.indexOf(stage); return <div className="mx-auto max-w-4xl overflow-hidden rounded-[26px] border bg-white shadow-[0_24px_70px_rgba(26,26,36,.08)]"><header className="border-b p-8 sm:p-10"><div className="flex justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-[#5549dd]">AI visibility audit in progress</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">{labels[stage]}</h1><p className="mt-3 break-all text-sm text-[#74737c]">{run?.audit.requested_url || "Loading audit…"}</p></div><span className="h-fit rounded-full bg-[#f1efff] px-4 py-2 font-mono font-semibold text-[#4b3fca]">{progress}%</span></div><div className="mt-7 h-2 rounded-full bg-[#efeee9]"><div className="h-full rounded-full bg-gradient-to-r from-[#5a4df4] to-[#ff5738]" style={{width:`${Math.max(2,progress)}%`}} /></div></header><div className="grid gap-8 p-8 sm:p-10 md:grid-cols-[1fr_280px]"><ol className="space-y-2">{stages.slice(1,-1).map((item,i)=>{const index=i+1,active=current===index||(stage==="queued"&&i===0),done=current>index;return <li key={item} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm ${active?"bg-[#f1efff] font-semibold text-[#4034bd]":"text-[#74737c]"}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${done?"bg-[#5a4df4] text-white":""}`}>{done?<CheckIcon className="h-4 w-4"/>:index}</span>{labels[item]}</li>})}</ol><aside className="rounded-2xl bg-[#f7f6f3] p-5"><h2 className="font-semibold">Evidence boundary</h2><p className="mt-3 text-sm leading-6 text-[#686871]">This checks your public site. It does not query private answer-engine systems or claim that a brand is currently cited.</p></aside></div></div> }
function Finding({item}:{item:VisibilityFinding}) { return <article className="rounded-[20px] border bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${severityStyle(item.severity)}`}>{item.severity}</span><span className="rounded-full bg-[#f2f0ff] px-2.5 py-1 text-xs font-semibold capitalize text-[#4b3fca]">{item.dimension.replace("_"," ")}</span></div><span className="font-mono text-sm font-semibold text-[#4b3fca]">{item.priority_score}/100</span></div><h3 className="mt-5 text-xl font-semibold">{item.title}</h3><p className="mt-3 leading-7 text-[#5f5e67]">{item.observation}</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-[#f7f6f3] p-4"><p className="text-xs font-semibold uppercase tracking-[.1em]">Why it matters</p><p className="mt-2 text-sm leading-6 text-[#686871]">{item.why_it_matters}</p></div><div className="rounded-xl bg-[#effaf4] p-4"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#267257]">Recommended fix</p><p className="mt-2 text-sm leading-6 text-[#49685b]">{item.recommendation}</p></div></div><details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-semibold text-[#5549dd]">Evidence and affected URLs</summary><ul className="mt-2 space-y-1 text-xs leading-5 text-[#777680]">{item.evidence.map(x=><li key={x}>• {x}</li>)}</ul></details></article> }
function Results({result}:{result:VisibilityResult}) { return <div><header className="flex flex-wrap justify-between gap-5 border-b pb-7"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#4b3fca]">AI visibility audit complete</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em]">Your evidence-backed scorecard</h1><p className="mt-3 break-all text-[#686871]">{result.requested_url}</p></div><Link href="/agents/ai-visibility" className="h-fit rounded-xl bg-[#171820] px-4 py-3 text-sm font-semibold text-white">Audit another site</Link></header>
  <section className="mt-7 grid gap-4 lg:grid-cols-[220px_1fr]"><div className="flex min-h-44 flex-col items-center justify-center rounded-[22px] bg-[#171820] text-white"><strong className="text-6xl tracking-[-.06em]">{result.overall_score}</strong><span className="mt-2 text-sm text-white/70">overall readiness</span></div><div className="grid gap-3 sm:grid-cols-2">{result.dimensions.map(d=><article key={d.dimension} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold capitalize">{d.dimension.replace("_"," ")}</h2><strong className="text-[#4b3fca]">{d.score}</strong></div><div className="mt-3 h-2 rounded bg-[#efeee9]"><div className="h-full rounded bg-[#5a4df4]" style={{width:`${d.score}%`}} /></div><p className="mt-3 text-xs leading-5 text-[#777680]">{d.summary}</p>{d.deductions.length?<details className="mt-2 text-xs text-[#a34831]"><summary className="cursor-pointer font-semibold">Show deductions</summary>{d.deductions.map(x=><p key={x} className="mt-1">{x}</p>)}</details>:null}</article>)}</div></section>
  <p className="mt-4 rounded-xl bg-[#f7f6f3] p-4 text-xs leading-5 text-[#686871]">{result.methodology}</p>
  <section className="mt-10"><h2 className="text-3xl font-semibold">Declared crawler policies</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{result.bot_policies.map(p=><article key={p.user_agent} className="rounded-2xl border bg-white p-4"><div className="flex justify-between gap-2"><strong>{p.user_agent}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${p.status==="blocked"?"bg-red-50 text-red-700":p.status==="allowed"?"bg-green-50 text-green-700":"bg-stone-100 text-stone-600"}`}>{p.status.replace("_"," ")}</span></div><p className="mt-3 text-xs leading-5 text-[#777680]">{p.evidence}</p></article>)}</div></section>
  <section className="mt-12"><h2 className="text-3xl font-semibold">Prioritized fixes</h2><div className="mt-6 grid gap-5">{result.findings.length?result.findings.map(x=><Finding key={x.id} item={x}/>):<div className="rounded-2xl border bg-white p-8 text-center text-[#686871]">No configured rule produced a finding in this sample.</div>}</div></section>
  <section className="mt-12"><h2 className="text-3xl font-semibold">Page scorecards</h2><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#f7f6f3] text-xs uppercase tracking-[.1em] text-[#777680]"><tr><th className="p-4">Page</th><th className="p-4">Score</th><th className="p-4">Words</th><th className="p-4">Schema</th><th className="p-4">Findings</th></tr></thead><tbody className="divide-y">{result.pages.map(p=><tr key={p.url}><td className="max-w-md p-4"><p className="font-semibold">{p.title}</p><p className="truncate text-xs text-[#85848b]">{p.url}</p></td><td className="p-4 font-semibold">{p.score}</td><td className="p-4">{p.word_count}</td><td className="p-4">{p.schema_types.join(", ")||"None observed"}</td><td className="p-4">{p.findings}</td></tr>)}</tbody></table></div></section>
  <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-900">Limitations and crawl notes</h2><ul className="mt-2 space-y-1 text-sm leading-6 text-amber-900">{[...result.limitations,...result.warnings].map(x=><li key={x}>• {x}</li>)}</ul></section>
 </div> }
export function AIVisibilityRun({auditId}:{auditId:string}) { const [run,setRun]=useState<VisibilityResponse|null>(null),[error,setError]=useState(""),[version,setVersion]=useState(0),[retrying,setRetrying]=useState(false); const started=useRef(false);
 useEffect(()=>{let cancelled=false,timer:ReturnType<typeof setTimeout>|undefined; async function poll(){try{const next=await getVisibilityAudit(auditId);if(cancelled)return;setRun(next);if(next.audit.status==="queued"&&!started.current){started.current=true;void processVisibilityAudit(auditId).catch(e=>{started.current=false;setError(e instanceof Error?e.message:"Could not process audit")})}if(next.audit.status==="running"||next.audit.status==="queued")timer=setTimeout(poll,1200)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Could not load audit")}}void poll();return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[auditId,version]);
 if(error&&!run)return <p className="rounded-xl bg-red-50 p-5 text-red-700">{error}</p>; if(!run||["queued","running"].includes(run.audit.status))return <Progress run={run}/>; if(run.audit.status==="failed")return <div className="mx-auto max-w-2xl rounded-2xl border bg-white p-8 text-center"><h1 className="text-3xl font-semibold">Audit failed</h1><p className="mt-3 text-red-700">{run.audit.error}</p><button disabled={retrying} onClick={async()=>{setRetrying(true);await retryVisibilityAudit(auditId);started.current=false;setVersion(v=>v+1);setRetrying(false)}} className="mt-5 rounded-xl bg-[#ff5738] px-5 py-3 font-semibold text-white">Retry audit</button></div>; return run.audit.result?<Results result={run.audit.result}/>:<Progress run={run}/> }
