import Link from "next/link";
import { AIVisibilityForm } from "@/components/ai-visibility-form";
import { CheckIcon } from "@/components/icons";

const benefits = [
  ["Access before polish", "Declared crawler policies and fetch failures surface before content recommendations."],
  ["Four separate dimensions", "Discoverability, machine readability, entity clarity, and citability stay distinct."],
  ["Reasons, not mystery scores", "Every deduction links to an observation, affected URLs, and a practical next step."],
  ["Entity context you control", "Optional business and product names let the audit test explicit naming without guessing."],
  ["Citation readiness with caveats", "Answer structure is assessed as a heuristic—not as a promise of inclusion in AI answers."],
  ["Saved, repeatable baselines", "Re-open reports from history and re-run after releases or remediation."],
];
const faqs = [
  ["What is an AI visibility audit?", "It assesses whether public pages are retrievable, structurally understandable, entity-clear, and formatted with extractable answers. The result is a transparent scorecard and fix list."],
  ["Will this guarantee my brand appears in ChatGPT answers?", "No. No on-site audit can guarantee an external answer engine's sourcing decision. This audit finds barriers and readiness signals on the website you control."],
  ["How is this different from a traditional SEO audit?", "It focuses on the answer-engine pipeline: declared crawler access, machine-readable meaning, entity clarity, and citability. It complements the broader SEO/AEO audit."],
  ["What does the agent need?", "A public URL. Business name, product name, priority pages, and audit goal are optional but make entity checks more specific."],
  ["Does it measure my presence on other sites?", "No. This run observes your own public site. Mentions, citations, and recommendations on third-party platforms are outside its evidence boundary."],
  ["What do the crawler results mean?", "They describe rules declared in robots.txt for named user agents at audit time. They do not reproduce every provider's complete fetching or answer pipeline."],
  ["Can I re-run it?", "Yes. Completed and failed audits can be queued again, while each saved report remains available from history."],
  ["Do I keep the report?", "Yes. When persistence is configured, the scorecard, findings, evidence, and limitations are saved in the shared agent history."],
];
function Cards({items}:{items:string[][]}) { return <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(([title,body])=><article key={title} className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-3 leading-7 text-[#686871]">{body}</p></article>)}</div> }
export function AIVisibilityAgentPage() { return <main>
  <section className="bg-[radial-gradient(circle_at_76%_20%,rgba(90,77,244,.10),transparent_34%),radial-gradient(circle_at_18%_18%,rgba(255,87,56,.08),transparent_28%)]"><div className="mx-auto max-w-[1280px] px-5 py-12 sm:px-8"><nav className="text-sm text-[#777680]"><Link href="/agents">Agents</Link><span className="mx-2">›</span>AI Visibility Audit Agent</nav><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_520px] lg:gap-16"><div><p className="font-mono text-xs font-semibold uppercase tracking-[.24em] text-[#d94221]">SEO agents</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.055em] sm:text-[58px]">AI Visibility Audit</h1><p className="mt-6 text-xl font-semibold leading-8">See whether AI search and answer engines can discover, understand, and cite your website—and what to fix first.</p><p className="mt-5 leading-7 text-[#686871]">Run an evidence-first URL audit across discoverability, machine readability, entity clarity, and citability. Every score shows its deductions and limitations.</p><ul className="mt-7 flex flex-wrap gap-5 text-sm font-semibold">{["Visibility scorecard","Prioritized fixes","Crawler policies","Citation readiness"].map(x=><li key={x} className="flex gap-2"><CheckIcon className="h-5 w-5 text-[#ff5738]" />{x}</li>)}</ul></div><AIVisibilityForm /></div></div></section>
  <section className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="text-4xl font-semibold tracking-[-.04em]">What this audit actually measures</h2><p className="mt-5 max-w-4xl leading-8 text-[#62626c]">The audit reads public HTML and declared crawler rules, then applies deterministic checks. It can identify barriers and improve extractability; it cannot observe private answer-engine systems or guarantee a citation.</p></section>
  <section className="border-y bg-white"><div className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="text-4xl font-semibold tracking-[-.04em]">Why use the agent</h2><Cards items={benefits} /></div></section>
  <section className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="text-4xl font-semibold tracking-[-.04em]">How it works</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{[["Enter a public URL","Add optional canonical names and priority pages."],["Collect live evidence","Crawl bounded pages, robots rules, HTML structure, and schema."],["Score transparently","Apply documented deductions across four dimensions."],["Fix and re-audit","Work from critical access issues through content opportunities."]].map(([t,b],i)=><article key={t} className="rounded-[20px] border bg-white p-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#5a4df4] text-white">{i+1}</span><h3 className="mt-5 text-xl font-semibold">{t}</h3><p className="mt-3 text-[#686871]">{b}</p></article>)}</div></section>
  <section className="border-y bg-white"><div className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="text-4xl font-semibold tracking-[-.04em]">What the agent generates</h2><Cards items={[["Visibility scorecard","Weighted dimensions with every deduction exposed."],["Prioritized fix list","Observation, importance, recommendation, evidence, and affected URLs."],["Crawler policy summary","Path-level robots.txt results for configured AI user-agent tokens."],["Structured-data gaps","Observed schema types and truthful opportunities."],["Citability notes","Heuristic flags for sparse or indirect answers."],["Limitations","What this bounded on-site audit cannot establish."]]} /></div></section>
  <section className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><h2 className="text-4xl font-semibold tracking-[-.04em]">Frequently asked questions</h2><div className="mt-8 divide-y rounded-[20px] border bg-white px-7">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none justify-between font-semibold">{q}<span className="text-[#5549dd] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-4xl text-sm leading-7 text-[#686871]">{a}</p></details>)}</div></section>
</main> }
