"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { getContentOptimizerRun, processContentOptimizerRun, retryContentOptimizerRun, type ContentOptimizerRun } from "@/lib/content-optimizer-api";

const priorityStyle={critical:"bg-red-100 text-red-800",high:"bg-orange-100 text-orange-800",medium:"bg-amber-100 text-amber-800",low:"bg-blue-100 text-blue-800"};
const statusStyle={good:"bg-green-50 text-green-700",review:"bg-amber-50 text-amber-800",not_assessed:"bg-stone-100 text-stone-600"};

function Progress({run}:{run:ContentOptimizerRun|null}){return <div className="mx-auto max-w-3xl rounded-3xl border bg-white p-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#5549dd]">Content review in progress</p><h1 className="mt-3 text-3xl font-semibold capitalize">{run?.stage.replaceAll("_"," ")||"Loading"}</h1><div className="mt-6 h-2 rounded-full bg-[#efeee9]"><div className="h-full rounded-full bg-gradient-to-r from-[#5a4df4] to-[#ff5738]" style={{width:`${Math.max(2,run?.progress||0)}%`}}/></div></div>}

function Result({run}:{run:ContentOptimizerRun}){const result=run.result!;const evidence=new Map(result.evidence.map(item=>[item.id,item]));const [copy,setCopy]=useState("Copy JSON");async function copyJson(){try{await navigator.clipboard.writeText(JSON.stringify(result,null,2));setCopy("Copied")}catch{setCopy("Copy failed")}}return <div>
  <header className="flex flex-wrap items-start justify-between gap-5 border-b pb-7"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#5549dd]">SEO content optimization</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em]">{result.target_keyword}</h1><p className="mt-3 text-[#686871]">For {result.audience} · {result.word_count} observed words</p>{result.source_url?<a href={result.source_url} target="_blank" rel="noreferrer" className="mt-2 block break-all text-sm text-[#5549dd] underline">{result.source_url}</a>:null}</div><div className="flex gap-2"><button onClick={copyJson} className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold">{copy}</button><Link href="/agents/content-optimizer" className="rounded-xl bg-[#171820] px-4 py-3 text-sm font-semibold text-white">Optimize another page</Link></div></header>
  <section className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><strong className="text-3xl">{result.overall_score??"—"}</strong><p className="mt-1 text-sm text-[#777680]">{result.overall_score===null?"not assessed":"assessed-check score"}</p></div><div className="rounded-2xl border bg-white p-5"><strong className="text-3xl">{result.actions.length}</strong><p className="mt-1 text-sm text-[#777680]">prioritized actions</p></div><div className="rounded-2xl border bg-white p-5"><strong className="text-3xl">{result.assessed_checks}/{result.total_checks}</strong><p className="mt-1 text-sm text-[#777680]">checks assessed</p></div></section>
  {result.warnings.length?<section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-900">Coverage notes</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-900">{result.warnings.map(item=><li key={item}>{item}</li>)}</ul></section>:null}
  <section className="mt-10"><h2 className="text-3xl font-semibold">Assessment coverage</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{result.assessments.map(item=><article key={item.key} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{item.label}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${statusStyle[item.status]}`}>{item.status.replace("_"," ")}</span></div><p className="mt-3 text-sm leading-6 text-[#686871]">{item.summary}</p></article>)}</div></section>
  <section className="mt-10"><h2 className="text-3xl font-semibold">Prioritized editorial actions</h2>{result.actions.length?<div className="mt-5 space-y-4">{result.actions.map((item,index)=><article key={item.id} className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-[#777680]">#{index+1}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${priorityStyle[item.priority]}`}>{item.priority}</span><span className="rounded-full bg-[#f2f0ff] px-2.5 py-1 text-[10px] font-semibold uppercase text-[#4b3fca]">{item.category}</span><span className="text-xs text-[#777680]">{item.effort} effort · {item.confidence} confidence</span></div><h3 className="mt-3 text-xl font-semibold">{item.issue}</h3><p className="mt-1 text-sm text-[#777680]">Affected: {item.affected_section}</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-[#f7f6f3] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#777680]">Observed</p><p className="mt-2 text-sm leading-6">{item.observed_text}</p></div><div className="rounded-xl bg-[#f2f0ff] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#5549dd]">Proposed action</p><p className="mt-2 text-sm leading-6">{item.proposed_action}</p></div></div><p className="mt-4 text-sm leading-6 text-[#686871]"><strong>Why it may help:</strong> {item.impact_rationale}</p>{item.evidence_ids.length?<details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-[#5549dd]">View supporting evidence</summary><ul className="mt-2 space-y-2">{item.evidence_ids.map(id=>{const source=evidence.get(id);return source?<li key={id} className="rounded-lg border p-3 text-xs"><strong>{source.label}</strong><p className="mt-1 text-[#686871]">{source.observed}</p>{source.source_url?<a href={source.source_url} target="_blank" rel="noreferrer" className="mt-1 block break-all text-[#5549dd] underline">{source.source_url}</a>:null}</li>:null})}</ul></details>:null}</article>)}</div>:<p className="mt-4 rounded-2xl border bg-white p-6 text-[#686871]">No actions were triggered by the assessed checks.</p>}</section>
  <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-900">Method limits</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-900">{result.limitations.map(item=><li key={item}>{item}</li>)}</ul></section>
  </div>}

export function ContentOptimizerRunView({runId}:{runId:string}){const [run,setRun]=useState<ContentOptimizerRun|null>(null),[error,setError]=useState(""),[version,setVersion]=useState(0),[busy,setBusy]=useState(false);const started=useRef(false);useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|undefined;async function poll(){try{const next=await getContentOptimizerRun(runId);if(cancelled)return;setRun(next);if(next.status==="queued"&&!started.current){started.current=true;void processContentOptimizerRun(runId).catch(caught=>{started.current=false;setError(caught instanceof Error?caught.message:"Could not start optimization.")})}if(next.status==="queued"||next.status==="running")timer=setTimeout(poll,1000)}catch(caught){if(!cancelled)setError(caught instanceof Error?caught.message:"Could not load optimization.")}}void poll();return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[runId,version]);if(error&&!run)return <p role="alert" className="rounded-xl bg-red-50 p-5 text-red-700">{error}</p>;if(!run||run.status==="queued"||run.status==="running")return <Progress run={run}/>;if(run.status==="failed")return <div className="mx-auto max-w-2xl rounded-2xl border bg-white p-8 text-center"><h1 className="text-3xl font-semibold">Optimization failed</h1><p className="mt-3 text-red-700">{run.error}</p><button disabled={busy} onClick={async()=>{setBusy(true);try{await retryContentOptimizerRun(runId);started.current=false;setVersion(value=>value+1)}finally{setBusy(false)}}} className="mt-5 rounded-xl bg-[#ff5738] px-5 py-3 font-semibold text-white disabled:opacity-50">Retry</button></div>;return run.result?<Result run={run}/>:<Progress run={run}/>}
