"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";

import { CheckIcon } from "@/components/icons";
import {
  getContentBrief, getContentBriefResult, processContentBrief, retryContentBrief,
  type ContentBriefResponse, type ContentBriefResult,
} from "@/lib/content-brief-api";

const stages = ["normalizing", "planning", "validating", "repairing", "finalizing"];
const labels: Record<string, string> = { queued: "Queued", normalizing: "Checking the assignment", planning: "Building the content strategy", validating: "Validating the writer handoff", repairing: "Repairing validation issues", finalizing: "Saving the complete brief", complete: "Complete", failed: "Failed" };

function Progress({ run }: { run: ContentBriefResponse | null }) {
  if (!run) return <div className="mx-auto max-w-3xl rounded-[24px] border border-[#dfdedb] bg-white p-10 shadow-[0_24px_70px_rgba(26,26,36,0.08)]"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#5549dd]">Loading saved run</p><h1 className="mt-3 text-3xl font-semibold">Retrieving your content brief…</h1><p className="mt-4 text-sm leading-6 text-[#74737c]">This screen does not start or regenerate anything until the saved run status has been loaded.</p></div>;
  const stage = run.generation.stage;
  const active = stages.indexOf(stage);
  return <div className="mx-auto max-w-3xl rounded-[24px] border border-[#dfdedb] bg-white p-7 shadow-[0_24px_70px_rgba(26,26,36,0.08)] sm:p-10"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#5549dd]">Content brief in progress</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">{labels[stage] ?? "Building your brief"}</h1><p className="mt-3 text-sm text-[#74737c]">{run.generation.request.target_keyword} · {run.generation.request.audience}</p></div><span className="font-mono text-sm text-[#777680]">{run.generation.progress}%</span></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-[#efeee9]"><div className="h-full rounded-full bg-gradient-to-r from-[#5a4df4] to-[#ff5738] transition-[width]" style={{ width: `${Math.max(run.generation.progress, 2)}%` }} /></div><ol className="mt-8 grid gap-3 sm:grid-cols-2">{stages.map((item, index) => { const done = active > index || stage === "complete"; const isActive = active === index || (stage === "queued" && index === 0); return <li key={item} className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-sm ${isActive ? "border-[#c7c1ff] bg-[#f3f1ff] font-semibold text-[#4034bd]" : "border-[#eceae6] text-[#74737c]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full ${done ? "bg-[#5a4df4] text-white" : "bg-[#f3f2ee]"}`}>{done ? <CheckIcon className="h-4 w-4" /> : index + 1}</span>{labels[item]}</li>; })}</ol><p className="mt-7 text-sm leading-6 text-[#74737c]">The model drafts strategy; code validates heading hierarchy, grounded URLs, duplicate sections, word budgets, and unsupported outcome promises.</p></div>;
}

function Results({ result }: { result: ContentBriefResult }) {
  const brief = result.brief;
  return <div><header className="flex flex-wrap items-start justify-between gap-5 border-b border-[#e3e1dc] pb-7"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-[#4b3fca]">Content brief complete</p><h1 className="mt-2 max-w-4xl text-4xl font-semibold tracking-[-0.045em] sm:text-[46px]">{brief.suggested_title}</h1><p className="mt-3 text-sm text-[#686871]">Target: {result.target_keyword} · Audience: {result.audience}</p></div><Link href="/agents/content-brief" className="rounded-xl bg-[#171820] px-4 py-3 text-sm font-semibold text-white">Create another brief</Link></header>
    <section className={`mt-8 rounded-[22px] border p-6 ${result.ready_for_handoff ? "border-[#bfe6cc] bg-[#eef9f2]" : "border-[#ffc9bc] bg-[#fff2ee]"}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold">{result.ready_for_handoff ? "Ready for writer handoff" : "Saved as a review draft"}</p><p className="mt-1 text-sm text-[#62626c]">{result.ready_for_handoff ? "No blocking validation issues remain. Editorial and factual review are still required." : "Resolve the blocking issues below before assigning this brief."}</p></div><span className="rounded-full bg-white px-4 py-2 font-mono text-sm font-semibold">Quality {result.quality_score}/100</span></div></section>
    <section className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["Intent", `${brief.search_intent} · ${brief.intent_confidence} confidence`], ["Format", brief.recommended_format], ["Target length", `${brief.target_word_count_min.toLocaleString()}–${brief.target_word_count_max.toLocaleString()} words`], ["Mode", result.content_mode === "rewrite" ? "Rewrite" : "New article"]].map(([name, value]) => <article key={name} className="rounded-2xl border border-[#dfdedb] bg-white p-5"><p className="font-mono text-[11px] uppercase tracking-[0.16em] text-[#777680]">{name}</p><p className="mt-2 font-semibold capitalize">{value}</p></article>)}</section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Strategy</h2><dl className="mt-4 space-y-4 text-sm leading-6"><div><dt className="font-semibold">Intent rationale</dt><dd className="mt-1 text-[#686871]">{brief.intent_rationale}</dd></div><div><dt className="font-semibold">Reader job</dt><dd className="mt-1 text-[#686871]">{brief.reader_job}</dd></div><div><dt className="font-semibold">Introduction</dt><dd className="mt-1 text-[#686871]">{brief.introduction_guidance}</dd></div><div><dt className="font-semibold">Tone</dt><dd className="mt-1 text-[#686871]">{brief.tone_and_voice.join(", ")}</dd></div></dl></article><article className="rounded-[20px] border border-[#d7d2f2] bg-[#f4f2ff] p-6"><h2 className="text-xl font-semibold">Evidence boundary</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-6 text-[#62626c]">{result.evidence_limitations.map((item) => <li key={item}>{item}</li>)}</ul></article></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Writer-ready outline</h2><div className="mt-4 space-y-4">{brief.outline.map((section, index) => <article key={`${section.heading}-${index}`} className={`rounded-[20px] border bg-white p-6 ${section.heading_level === "H3" ? "ml-5 border-[#dedaf8]" : "border-[#dfdedb]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="font-mono text-xs font-semibold text-[#5549dd]">{section.heading_level}</span><h3 className="mt-1 text-xl font-semibold">{section.heading}</h3></div><span className="rounded-full bg-[#f1f0ec] px-3 py-1 text-xs text-[#666670]">~{section.suggested_words} words</span></div><p className="mt-3 text-sm leading-6 text-[#686871]">{section.purpose}</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-6">{section.talking_points.map((point) => <li key={point}>{point}</li>)}</ul>{section.questions_answered.length ? <p className="mt-3 text-xs leading-5 text-[#777680]"><strong>Questions:</strong> {section.questions_answered.join(" · ")}</p> : null}</article>)}</div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Coverage checklist</h2><ul className="mt-4 space-y-3">{brief.coverage.map((item) => <li key={`${item.name}-${item.item_type}`} className="rounded-xl bg-[#faf9f7] p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{item.name}</span><span className="rounded-full bg-[#efedff] px-2 py-0.5 text-[10px] font-semibold uppercase text-[#5549dd]">{item.item_type}</span><span className="text-[10px] uppercase text-[#85848b]">{item.source}</span></div><p className="mt-1 text-sm leading-6 text-[#686871]">{item.why_include}</p></li>)}</ul></article><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">FAQ guidance</h2>{brief.faqs.length ? <div className="mt-4 divide-y divide-[#e8e6e1]">{brief.faqs.map((faq) => <div key={faq.question} className="py-4 first:pt-0"><h3 className="font-semibold">{faq.question}</h3><p className="mt-1 text-sm leading-6 text-[#686871]">{faq.answer_guidance}</p><span className="mt-1 inline-block text-[10px] uppercase text-[#85848b]">{faq.source}</span></div>)}</div> : <p className="mt-3 text-sm text-[#686871]">No FAQ section was recommended.</p>}</article></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Internal link plan</h2>{brief.internal_links.length ? <ul className="mt-4 space-y-4">{brief.internal_links.map((link) => <li key={link.target_url}><a href={link.target_url} target="_blank" rel="noreferrer" className="break-all font-semibold text-[#4b3fca]">{link.target_url}</a><p className="mt-1 text-sm"><strong>Anchor:</strong> {link.anchor_direction}</p><p className="text-sm"><strong>Place under:</strong> {link.placement_heading}</p><p className="mt-1 text-sm leading-6 text-[#686871]">{link.reason}</p></li>)}</ul> : <p className="mt-3 text-sm leading-6 text-[#686871]">No grounded links were added. Supply existing URLs in a new run to receive a link plan.</p>}</article><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Conversion notes</h2>{brief.conversion_notes.length ? <ul className="mt-4 space-y-4">{brief.conversion_notes.map((note) => <li key={`${note.call_to_action}-${note.placement_heading}`}><p className="font-semibold">{note.call_to_action}</p><p className="mt-1 text-sm">Place under: {note.placement_heading}</p><p className="mt-1 text-sm leading-6 text-[#686871]">{note.rationale}</p></li>)}</ul> : <p className="mt-3 text-sm leading-6 text-[#686871]">No CTA was added because none was supported by the assignment—or the intent did not call for one.</p>}</article></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Writer checks</h2><ul className="mt-4 space-y-2">{brief.writer_checks.map((item) => <li key={item} className="flex gap-2 text-sm leading-6"><CheckIcon className="mt-1 h-4 w-4 shrink-0 text-[#ff5738]" />{item}</li>)}</ul></article><article className="rounded-[20px] border border-[#dfdedb] bg-white p-6"><h2 className="text-xl font-semibold">Assumptions and validation</h2>{brief.assumptions.length ? <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-6 text-[#686871]">{brief.assumptions.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-3 text-sm text-[#686871]">No extra assumptions were recorded.</p>}{result.issues.length ? <div className="mt-5 border-t border-[#e8e6e1] pt-4">{result.issues.map((issue) => <p key={`${issue.code}-${issue.message}`} className={`mt-2 text-sm leading-6 ${issue.severity === "error" ? "text-red-700" : "text-amber-700"}`}><strong className="capitalize">{issue.severity}:</strong> {issue.message}</p>)}</div> : null}</article></section>
  </div>;
}

export function ContentBriefRun({ generationId }: { generationId: string }) {
  const [run, setRun] = useState<ContentBriefResponse | null>(null);
  const [result, setResult] = useState<ContentBriefResult | null>(null);
  const [error, setError] = useState("");
  const [version, setVersion] = useState(0);
  const [retrying, setRetrying] = useState(false);
  const processStarted = useRef(false);
  useEffect(() => { let cancelled = false; let timer: ReturnType<typeof setTimeout> | undefined; async function poll() { try { const next = await getContentBrief(generationId); if (cancelled) return; setRun(next); if (next.generation.status === "queued" && !processStarted.current) { processStarted.current = true; void processContentBrief(generationId).catch((caught) => { if (!cancelled) { processStarted.current = false; setError(caught instanceof Error ? caught.message : "The run could not be started."); } }); } if (next.generation.status === "complete") { setResult(await getContentBriefResult(generationId)); return; } if (next.generation.status === "failed") { setError(next.generation.error ?? "The content brief failed."); return; } timer = setTimeout(poll, 1400); } catch (caught) { if (!cancelled) setError(caught instanceof Error ? caught.message : "Unable to load this run."); } } void poll(); return () => { cancelled = true; if (timer) clearTimeout(timer); }; }, [generationId, version]);
  async function retry() { setRetrying(true); try { if (run?.generation.status === "failed") await retryContentBrief(generationId); setError(""); setRun(null); setResult(null); processStarted.current = false; setVersion((value) => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : "The run could not be retried."); } finally { setRetrying(false); } }
  if (error) return <div className="mx-auto max-w-2xl rounded-[22px] border border-red-200 bg-white p-8 text-center"><p className="font-mono text-xs uppercase tracking-[0.18em] text-red-600">Brief unavailable</p><h1 className="mt-3 text-3xl font-semibold">We couldn&apos;t finish this run.</h1><p role="alert" className="mt-4 leading-7 text-[#696972]">{error}</p><div className="mt-7 flex justify-center gap-3"><button type="button" onClick={retry} disabled={retrying} className="rounded-xl bg-[#ff5738] px-5 py-3 font-semibold text-white">{retrying ? "Retrying…" : "Retry this run"}</button><Link href="/agents/content-brief" className="rounded-xl border border-[#d9d8d4] px-5 py-3 font-semibold">Start again</Link></div></div>;
  return result ? <Results result={result} /> : <Progress run={run} />;
}
